export interface BibleIncipit {
  es: string;
  la: string;
}

export const BIBLE_INCIPITS: Record<string, BibleIncipit> = {
  '01': { es: 'Lectura del libro del Génesis', la: 'Léctio libri Génesis' },
  '02': { es: 'Lectura del libro del Éxodo', la: 'Léctio libri Exodi' },
  '03': { es: 'Lectura del libro del Levítico', la: 'Léctio libri Levitici' },
  '04': { es: 'Lectura del libro de los Números', la: 'Léctio libri Numeri' },
  '05': { es: 'Lectura del libro del Deuteronomio', la: 'Léctio libri Deuteronómii' },
  '06': { es: 'Lectura del libro de Josué', la: 'Léctio libri Iosue' },
  '07': { es: 'Lectura del libro de los Jueces', la: 'Léctio libri Iudicum' },
  '08': { es: 'Lectura del libro de Rut', la: 'Léctio libri Ruth' },
  '09': { es: 'Lectura del primer libro de Samuel', la: 'Léctio libri primi Samuelis' },
  '10': { es: 'Lectura del segundo libro de Samuel', la: 'Léctio libri secundi Samuelis' },
  '11': { es: 'Lectura del primer libro de los Reyes', la: 'Léctio libri primi Regum' },
  '12': { es: 'Lectura del segundo libro de los Reyes', la: 'Léctio libri secundi Regum' },
  '13': { es: 'Lectura del primer libro de las Crónicas', la: 'Léctio libri primi Paralipomenon' },
  '14': { es: 'Lectura del segundo libro de las Crónicas', la: 'Léctio libri secundi Paralipomenon' },
  '15': { es: 'Lectura del libro de Esdras', la: 'Léctio libri Esdrae' },
  '16': { es: 'Lectura del libro de Nehemías', la: 'Léctio libri Nehemiae' },
  '17': { es: 'Lectura del libro de Tobías', la: 'Léctio libri Tobiae' },
  '18': { es: 'Lectura del libro de Judit', la: 'Léctio libri Iudith' },
  '19': { es: 'Lectura del libro de Ester', la: 'Léctio libri Esther' },
  '20': { es: 'Lectura del primer libro de los Macabeos', la: 'Léctio libri primi Machabaeorum' },
  '21': { es: 'Lectura del segundo libro de los Macabeos', la: 'Léctio libri secundi Machabaeorum' },
  '22': { es: 'Lectura del libro de Job', la: 'Léctio libri Iob' },
  '23': { es: 'Lectura del libro de los Salmos', la: 'Léctio libri Psalmorum' },
  '24': { es: 'Lectura del libro de los Proverbios', la: 'Léctio libri Proverbiorum' },
  '25': { es: 'Lectura del libro del Eclesiastés', la: 'Léctio libri Ecclesiastae' },
  '26': { es: 'Lectura del Cantar de los Cantares', la: 'Léctio Cántici Canticorum' },
  '27': { es: 'Lectura del libro de la Sabiduría', la: 'Léctio libri Sapientiae' },
  '28': { es: 'Lectura del libro del Eclesiástico', la: 'Léctio libri Ecclesiastici' },
  '29': { es: 'Lectura del libro de Isaías', la: 'Léctio libri Isaiae' },
  '30': { es: 'Lectura del libro de Jeremías', la: 'Léctio libri Ieremiae' },
  '31': { es: 'Lectura del libro de las Lamentaciones', la: 'Léctio Lamentationum' },
  '32': { es: 'Lectura del libro de Baruc', la: 'Léctio libri Baruch' },
  '33': { es: 'Lectura del libro de Ezequiel', la: 'Léctio libri Ezechielis' },
  '34': { es: 'Lectura del libro de Daniel', la: 'Léctio libri Danielis' },
  '35': { es: 'Lectura del libro de Oseas', la: 'Léctio libri Osee' },
  '36': { es: 'Lectura del libro de Joel', la: 'Léctio libri Ioel' },
  '37': { es: 'Lectura del libro de Amós', la: 'Léctio libri Amos' },
  '38': { es: 'Lectura del libro de Abdías', la: 'Léctio libri Abdiae' },
  '39': { es: 'Lectura del libro de Jonás', la: 'Léctio libri Ionae' },
  '40': { es: 'Lectura del libro de Miqueas', la: 'Léctio libri Michaeae' },
  '41': { es: 'Lectura del libro de Nahúm', la: 'Léctio libri Nahum' },
  '42': { es: 'Lectura del libro de Habacuc', la: 'Léctio libri Habacuc' },
  '43': { es: 'Lectura del libro de Sofonías', la: 'Léctio libri Sophoniae' },
  '44': { es: 'Lectura del libro de Ageo', la: 'Léctio libri Aggaei' },
  '45': { es: 'Lectura del libro de Zacarías', la: 'Léctio libri Zachariae' },
  '46': { es: 'Lectura del libro de Malaquías', la: 'Léctio libri Malachiae' },
  '47': { es: 'Lectura del santo Evangelio según san Mateo', la: 'Léctio sancti Evangélii secúndum Matthaeum' },
  '48': { es: 'Lectura del santo Evangelio según san Marcos', la: 'Léctio sancti Evangélii secúndum Marcum' },
  '49': { es: 'Lectura del santo Evangelio según san Lucas', la: 'Léctio sancti Evangélii secúndum Lucam' },
  '50': { es: 'Lectura del santo Evangelio según san Juan', la: 'Léctio sancti Evangélii secúndum Ioannem' },
  '51': { es: 'Lectura del libro de los Hechos de los Apóstoles', la: 'Léctio Actuum Apostolorum' },
  '52': { es: 'Lectura de la carta del apóstol san Pablo a los Romanos', la: 'Léctio Epístolae beáti Pauli apóstoli ad Romanos' },
  '53': { es: 'Lectura de la primera carta del apóstol san Pablo a los Corintios', la: 'Léctio Epístolae primae beáti Pauli apóstoli ad Corinthios' },
  '54': { es: 'Lectura de la segunda carta del apóstol san Pablo a los Corintios', la: 'Léctio Epístolae secúndae beáti Pauli apóstoli ad Corinthios' },
  '55': { es: 'Lectura de la carta del apóstol san Pablo a los Gálatas', la: 'Léctio Epístolae beáti Pauli apóstoli ad Galatas' },
  '56': { es: 'Lectura de la carta del apóstol san Pablo a los Efesios', la: 'Léctio Epístolae beáti Pauli apóstoli ad Ephesios' },
  '57': { es: 'Lectura de la carta del apóstol san Pablo a los Filipenses', la: 'Léctio Epístolae beáti Pauli apóstoli ad Philippenses' },
  '58': { es: 'Lectura de la carta del apóstol san Pablo a los Colosenses', la: 'Léctio Epístolae beáti Pauli apóstoli ad Colossenses' },
  '59': { es: 'Lectura de la primera carta del apóstol san Pablo a los Tesalonicenses', la: 'Léctio Epístolae primae beáti Pauli apóstoli ad Thessalonicenses' },
  '60': { es: 'Lectura de la segunda carta del apóstol san Pablo a los Tesalonicenses', la: 'Léctio Epístolae secúndae beáti Pauli apóstoli ad Thessalonicenses' },
  '61': { es: 'Lectura de la primera carta del apóstol san Pablo a Timoteo', la: 'Léctio Epístolae primae beáti Pauli apóstoli ad Timotheum' },
  '62': { es: 'Lectura de la segunda carta del apóstol san Pablo a Timoteo', la: 'Léctio Epístolae secúndae beáti Pauli apóstoli ad Timotheum' },
  '63': { es: 'Lectura de la carta del apóstol san Pablo a Tito', la: 'Léctio Epístolae beáti Pauli apóstoli ad Titum' },
  '64': { es: 'Lectura de la carta del apóstol san Pablo a Filemón', la: 'Léctio Epístolae beáti Pauli apóstoli ad Philemonem' },
  '65': { es: 'Lectura de la carta a los Hebreos', la: 'Léctio Epístolae ad Hebraeos' },
  '66': { es: 'Lectura de la carta del apóstol Santiago', la: 'Léctio Epístolae Iacobi' },
  '67': { es: 'Lectura de la primera carta del apóstol san Pedro', la: 'Léctio Epístolae primae Petri' },
  '68': { es: 'Lectura de la segunda carta del apóstol san Pedro', la: 'Léctio Epístolae secúndae Petri' },
  '69': { es: 'Lectura de la primera carta del apóstol san Juan', la: 'Léctio Epístolae primae Ioannis' },
  '70': { es: 'Lectura de la segunda carta del apóstol san Juan', la: 'Léctio Epístolae secúndae Ioannis' },
  '71': { es: 'Lectura de la tercera carta del apóstol san Juan', la: 'Léctio Epístolae tertiae Ioannis' },
  '72': { es: 'Lectura de la carta del apóstol san Judas', la: 'Léctio Epístolae Iudae' },
  '73': { es: 'Lectura del libro del Apocalipsis del apóstol san Juan', la: 'Léctio libri Apocalypsis beáti Ioannis apóstoli' },
};

